# Generated by Django 5.1.7 on 2025-03-10 22:09

from django.db import migrations


def create_default_chatrooms(apps, schema_editor):
    ChatRoom = apps.get_model("chat", "ChatRoom")
    ChatRoom.objects.bulk_create(
        [ChatRoom(name="general"), ChatRoom(name="random")], ignore_conflicts=True
    )  # ignore_conflicts=True prevents errors if rooms already exist


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chatroom_alter_message_user_message_room"),
    ]

    operations = [
        migrations.RunPython(create_default_chatrooms),
    ]
